// ======= DO NOT EDIT THIS FILE ============
string trim(string s);
void split(string s, string a[], int &n); //split a string into array of strings
bool isInteger(string u);
bool isDouble(string u);
int toInteger(string u);
double toDouble(string u, int k=2); // Chuyen ve so thuc co k so le sau dau cham thap phan
string toDoubleStr(string u, int k=2); // Chuyen ve so thuc co k so le sau dau cham thap phan nhung o dang string
void display(string a[], int n);
void display(int a[], int n);
void display(double a[], int n);
bool exist(char * fname); // Check existence of a file
void viewFile(char *fname); //Read and display on the screen the content of  the file fname
void viewFileIgnoreBLlines(char *fname);  // view file ignoring blank lines
string readLineToStr(char * fname , int k); //Read and return line k (k=0,1,2,...) on the file fname
void readLineToStrArray(char * fname , int k, string a[], int &n); //Read line k (k=0,1,2,...) and extracts it to the array of strings
void readLineToIntArray(char * fname , int k, int a[], int &n);//Read line k (k=0,1,2,...) and extracts it to the array of integers
void readLineToDoubleArray(char * fname , int k, double a[], int &n);//Read line k (k=0,1,2,...) and extracts it to the array of double numbers
//================================================================================
string trim(string s)
 {string x="";
  char a[100]; strcpy(a,s.c_str());
  int i,j,r;i=0;j=strlen(a)-1;
  while(a[i]==' ' || a[i]=='\r' || a[i]=='\n') i++;
  while(a[j]==' ' || a[j]=='\r' || a[j]=='\n') j--;
  for(r=i;r<=j;r++) x += a[r];
  return(x);
 }

//split a string into array of strings
void split(string s, string a[], int &n)
 {int i,j,m; string x;
 s = trim(s);
  m = s.length();//s.size()
  i=0;j=0;
  while(i<m)
   {while(i<m && s.at(i)==' ') i++;
    x="";
    while(i<m && s.at(i) !=' ') x += s.at(i++);
    a[j++]=x;
   }
  n = j;
 }

//split a string into array of strings with a given separator character
void split(string s, string a[], int &n, char ch)
 {int i,j,m; string x;
 s = trim(s);
  m = s.length();//s.size()
  i=0;j=0;
cout<<" m = "<<m<<endl;
  while(i<m)
   {while(i<m && s.at(i) ==ch) i++;
    x="";
    while(i<m && s.at(i) !=ch)  x += s.at(i++);
    a[j++]=trim(x);
   }
  n = j;
 }

bool isInteger(string u)
   {u = trim(u);
    int i,n;
    n = u.length();
    char a[20]; strcpy(a,u.c_str());
    for(i=0;i<n;i++) if(isalpha(a[i])) return(false);
    return(true);
   }
bool isDouble(string u)
   {u = trim(u);
    int i,n,t; char x;
    n = u.length();
    char a[20]; strcpy(a,u.c_str());
    t=0;
    for(i=0;i<n;i++) if(a[i]=='.') t++;
    if(t>1) return(false);
    for(i=0;i<n;i++) 
      {x=a[i];
       if(x != '.' && isalpha(x)) return(false);
      }
    return(true);
   }
int toInteger(string u)
  {assert(isInteger(u));
   u = trim(u);
   char x[20]; strcpy(x,u.c_str());
   return(atoi(x));
  }
double toDouble(string u, int k) // Chuyen ve so thuc co k so le sau dau cham thap phan
  {assert(isDouble(u));
   u = trim(u);int n,i,j;
   n = u.size();
   char x[20]; strcpy(x,u.c_str());
   i=0;
   while(x[i] != '.') i++;
   j = i+k+1;
   if(j<n) n = j;
   x[n] = '\0';
   return(atof(x));
  }

string toDoubleStr(string u, int k) // Chuyen ve so thuc co k so le sau dau cham thap phan nhung o dang string
  {assert(isDouble(u));
   u = trim(u);int n,i,j;
   n = u.size();
   char x[20]; strcpy(x,u.c_str());
   i=0;
   while(x[i] != '.') i++;
   j = i+k+1;
   if(j<n) n = j;
   x[n] = '\0';
   string y(x);
   return(y);
  }

void display(string a[], int n)
 {for(int i=0;i<n;i++) cout<<a[i]<<endl;
 }
void display(int a[], int n)
 {for(int i=0;i<n;i++) cout<<a[i]<<endl;
 }
void display(double a[], int n)
 {for(int i=0;i<n;i++) cout<<a[i]<<endl;
 }

bool exist(char * fname) // Check existence of a file
 {fstream g(fname);
  if(g.is_open()) return(true); else return(false);
 }

//Read and display on the screen the content of  the file fname
  void viewFile(char *fname) 
   {ifstream fin(fname);
    if(!fin.is_open())
      {cout<<"\nThe file "<<fname<<" does not exist!"<<endl;
       return;
      }
    string s;
    cout<<"\nContent of the file "<<fname<<":"<<endl;
    while(fin.good())
     {getline(fin,s,'\n');
      s=trim(s);
      cout<<s<<endl;
     }
    fin.close();
   }

  void viewFileIgnoreBLlines(char *fname) // view file ignoring blank lines
   {ifstream fin(fname);
    if(!fin.is_open())
      {cout<<"\nThe file "<<fname<<" does not exist!"<<endl;
       return;
      }
    string s;
    cout<<"\nContent of the file "<<fname<<":"<<endl;
    while(fin.good())
     {getline(fin,s,'\n');
      s = trim(s);
      if(s.size()==0) continue;
      cout<<s<<endl;
     }
    fin.close();
   }

//Read and return line k (k=0,1,2,...) on the file fname
  string readLineToStr(char * fname , int k)
   {ifstream fin(fname);
    string s;
    for(int i=0;i<k;i++) getline(fin,s,'\n');
    getline(fin,s,'\n');
    fin.close();
    return(s);
   }


//Read line k (k=0,1,2,...) and extracts it to the array of strings
  void readLineToStrArray(char * fname , int k, string a[], int &n)
   {ifstream fin(fname);
    string s;
    for(int i=0;i<k;i++) getline(fin,s,'\n');
    getline(fin,s,'\n');
    fin.close();
    split(s,a,n);
   }


//Read line k (k=0,1,2,...) and extracts it to the array of integers
  void readLineToIntArray(char * fname , int k, int a[], int &n)
   {ifstream fin(fname);
    string s,b[100];int i;
    for(i=0;i<k;i++) getline(fin,s,'\n');
    getline(fin,s,'\n');
    fin.close();
    split(s,b,n);char x[20];
    for(i=0;i<n;i++) 
     {strcpy(x,b[i].c_str());
      a[i] = atoi(x);
     }
   }

//Read line k (k=0,1,2,...) and extracts it to the array of double numbers
  void readLineToDoubleArray(char * fname , int k, double a[], int &n)
   {ifstream fin(fname);
    string s,b[100];int i;
    for(i=0;i<k;i++) getline(fin,s,'\n');
    getline(fin,s,'\n');
    fin.close();
    split(s,b,n);char x[20];
    for(i=0;i<n;i++) 
     {strcpy(x,b[i].c_str());
      a[i] = atof(x);
     }
   }
